[package]
name = "tache"
version = "0.1.0"
authors = ["zhsyourai <mysoftzhs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
log = { version = "0.4", features = ["std"] }
time = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
signal = "0.6"
libc = "0.2"
rand = "0.6"
fnv = "1"
net2 = "0.2"
yaml-rust = "0.4"
igd = "^0.8.2"
siphasher = "0.3"
daemonize = "0.3"
ring = "0.14"
base-62 = "0.1"
http = "0.1"
http-body = "0.2.0-alpha.1"
async-std = "0.99"

[build-dependencies]
rustc_tools_util = "0.2.0"
